modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="ars_zero"
version="1.4.1"
displayName="Ars Zero"
authors="zeroregard"
description='''
A mod focused on staff-based spellcasting with temporal context for Ars Nouveau.
'''

[[mixins]]
config="ars_zero.mixins.json"

[[dependencies.ars_zero]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ars_zero]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ars_zero]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[1.21.1-5.9,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ars_zero]]
    modId="curios"
    mandatory=true
    versionRange="[9.0.14,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.ars_zero]]
    modId="player_animation_library"
    mandatory=true
    versionRange="[1.0.14,)"
    ordering="AFTER"
    side="BOTH"